export const SELECT_COUNTRY = "SELECT_COUNTRY";
export const FILTER_COUNTRY_LIST = "FILTER_COUNTRY_LIST";
export const RESET_COUNTRY_LIST = "RESET_COUNTRY_LIST";
export const GET_VERIFICATION_CODE = "GET_VERIFICATION_CODE";
export const VERIFICATION_CODE_SENT = "VERIFICATION_CODE_SENT";
export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER";
export const AUTH_LOG_IN = "AUTH_LOG_IN";
export const AUTH_LOG_IN_ERROR = "AUTH_LOG_IN_ERROR";
export const CLEAR_AUTH_LOG_IN_ERROR = "CLEAR_AUTH_LOG_IN_ERROR";
export const SET_TOKEN_ON_APP_START = "SET_TOKEN_ON_APP_START";
export const SIGN_OUT = "SIGN_OUT";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECEIVE_SOCKET_MESSAGE = "RECEIVE_SOCKET_MESSAGE";
export const SENT_SOCKET_MESSAGE = "SENT_SOCKET_MESSAGE";
export const GET_MSG_FROM_SERVER = "GET_MSG_FROM_SERVER";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const contactsTypes = {
  ADD_CONTACT: "ADD_CONTACT",
  GET_CONTACT: "GET_CONTACT",
  FILTER_CONTACT_LIST: "FILTER_CONTACT_LIST",
  PULL_PHONE_CONTACT_LIST: "PULL_PHONE_CONTACT_LIST",
};

export const userProfileTypes = {
  SET_NAME: "SET_NAME",
  SET_EMAIL: "SET_EMAIL",
  SET_DOB: "SET_DOB",
  SET_IMAGE: "SET_IMAGE",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  SET_USERPROFILE_SET: "SET_USERPROFILE_SET",
  GET_USERPROFILE: "GET_USERPROFILE",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
};
export const recentConversationTypes = {
  GET_CONVERSATION: "GET_CONVERSATION",
};

export const pushNoticicationTypes = {
  SET_TOKEN: "SET_TOKEN",
  SET_CONVERSATIONID: "SET_CONVERSATIONID",
  RESET_CONVERSATIONID: "RESET_CONVERSATIONID",
};

export const groupMessageTypes = {
  RECEIVE_GROUP_MSG_FROM_SERVER: "RECEIVE_GROUP_MSG_FROM_SERVER",
  GET_GROUP_FROM_SERVER: "GET_GROUP_FROM_SERVER",
  GET_GROUP_MSG_FROM_SERVER: "GET_GROUP_MSG_FROM_SERVER",
  CLEAR_GROUP_MESSAGE: "CLEAR_GROUP_MESSAGE",
};
